// FAQ content for /faq/ and /en/faq/. Edit here, then run `node scripts/seo/build.js`.
// Every answer was checked against the iOS app as of 2026-10-04.
// Values that can change without an app update (trial length, betas) are left out on purpose.
// Answers may use only <a>, <b>, <strong>, <br>, <ul>, <ol>, <li>, <p>.
const updated = '2026-10-05';

const ja = {
  path: '/faq/',
  home: '/',
  htmlLang: 'ja',
  ogLocale: 'ja_JP',
  ogImage: '/img/ogp.png?v=3',
  appStore: 'https://apps.apple.com/jp/app/id1482592304',
  title: 'よくある質問 | Texter - AI文字起こし・議事録アプリ',
  description: 'Texterの対応端末・料金・対応言語・話者識別・Apple Watch録音・ファイル取り込み・データの扱いなど、よくある質問への回答をまとめています。',
  h1: 'よくある質問',
  intro: 'Texter（AI文字起こし・議事録アプリ）について、よくいただく質問への回答です。画面ごとの操作手順は<a href="https://texter-app.notion.site/faq-ja" target="_blank" rel="noopener noreferrer">使い方ガイド（Notion）</a>にまとめています。',
  updatedLabel: '最終更新',
  tocTitle: '目次',
  crumb: 'よくある質問',
  crumbLabel: 'パンくずリスト',
  skip: '本文へスキップ',
  navLabel: 'メイン',
  nav: [
    { label: '機能', href: '/#record', opt: true },
    { label: '料金', href: '/#pricing', opt: true },
    { label: 'EN', href: '/en/faq/', hreflang: 'en' },
  ],
  ctaTitle: '次の会議から、録るだけ。',
  ctaBody: 'Texterは無料で始められます。iPhone / iPad / Apple Watch / Mac (Apple Silicon) / Android対応。',
  footer: [
    { label: 'ホーム', href: '/' },
    { label: '使い方ガイド', href: 'https://texter-app.notion.site/faq-ja', ext: true },
    { label: 'お問い合わせ', href: 'mailto:texter.work.app@gmail.com' },
    { label: '利用規約', href: '/terms-of-service/' },
    { label: 'プライバシーポリシー', href: '/privacy-policy/' },
    { label: '特定商取引法に基づく表記', href: '/tokushoho/' },
    { label: 'English', href: '/en/faq/', hreflang: 'en' },
  ],
  sections: [
    {
      id: 'about', title: 'Texterについて', items: [
        { id: 'what-is-texter', q: 'Texterはどんなアプリですか？',
          a: '<p>会議・取材・講義などの音声を文字にする、AI文字起こし・議事録アプリです。録音または音声・動画ファイルの取り込みから、文字起こし・話者識別・要約・アクションアイテム（タスク）の抽出までを自動で行います。保存したノートには、あとからAIチャットで質問できます。</p>' },
        { id: 'devices', q: 'どの端末で使えますか？',
          a: '<ul><li>iPhone・iPad（iOS / iPadOS 16.0以降）</li><li>Apple Watch（watchOS 11以降）</li><li>Apple Silicon搭載のMac（iPad版アプリとして動作）</li><li>Android（Google Playで配信）</li></ul>' },
        { id: 'price', q: '無料で使えますか？料金はいくらですか？',
          a: '<p>アプリのダウンロードと基本機能は無料です。無料版には、文字起こしの時間や各機能の利用回数に上限があります。</p><p>上限を引き上げるTexter Premiumは、App Store（日本）で月額 ¥1,800、年額 ¥8,800、週額 ¥600 です。無料トライアルの有無と期間は、アプリ内の購入画面でご確認ください。</p>' },
        { id: 'cancel', q: 'Premiumの解約はどうすればいいですか？',
          a: '<p>iPhoneの「設定」→ 自分の名前 →「サブスクリプション」→「Texter」から解約できます。Androidでは、Google Playの「お支払いと定期購入」→「定期購入」から解約します。アプリを削除しただけでは解約されません。</p>' },
        { id: 'business', q: '法人で利用できますか？',
          a: '<p>はい。機能・料金・セキュリティ情報をまとめた<a href="/assets/pdf/texter-for-business.pdf">法人向け資料（PDF）</a>をご用意しています。ご相談は<a href="mailto:texter.work.app@gmail.com">texter.work.app@gmail.com</a>までお送りください。</p>' },
      ],
    },
    {
      id: 'transcription', title: '文字起こし', items: [
        { id: 'realtime', q: '会議をその場でリアルタイムに文字起こしできますか？',
          a: '<p>できます。録音ボタンを押すと、話している内容がその場で文字になります。言語と設定に応じて、会話向けのクラウド音声認識エンジンか、Appleの音声認識を使います。無料版は1回の録音で使える時間に上限があります。</p>' },
        { id: 'import', q: '録音済みの音声や動画ファイルも文字起こしできますか？対応形式は？',
          a: '<p>できます。対応しているファイル形式は次のとおりです。</p><ul><li>音声：m4a、mp3、wav、aac、aiff、cafなど</li><li>動画：mp4、mov、m4v</li></ul><p>Googleドライブ・Dropbox・OneDriveの共有リンクからも取り込めます。文字起こしエンジンは、Whisper（OpenAIの音声認識モデル）、Amazon Transcribe、端末内で処理するApple SpeechAnalyzer（iOS 26以降）から選べます。Premiumでは、1ファイルあたりWhisperで最長2時間、Amazon Transcribeで最長4時間まで処理できます。Amazon Transcribeは、ファイルの長さとは別に月ごとの利用時間の枠があります。</p>' },
        { id: 'speaker-diarization', q: '話者識別（誰が話したかの区別）はできますか？',
          a: '<p>Premiumでご利用いただけます。音声・動画ファイルをWhisperまたはAmazon Transcribeで文字起こしするときに、話者ごとに発言を分けて記録します。Amazon Transcribeは最大10人まで区別します。</p>' },
        { id: 'languages', q: '何語に対応していますか？',
          a: '<p>ファイルの文字起こし（Whisper）は99言語と言語の自動判定に対応しています。リアルタイム文字起こしは、Appleの音声認識が対応する言語で使えます。翻訳はDeepLとGoogle翻訳から選べます。</p>' },
        { id: 'offline', q: 'オフラインでも使えますか？',
          a: '<p>一部の機能は使えます。リアルタイム文字起こしは、ネットワークにつながっていないときに端末内のApple音声認識へ切り替わります（端末内認識に対応した言語のみ）。iOS 26以降では、ファイルの文字起こしに端末内で処理するSpeechAnalyzerを選べます。翻訳はGoogleのオフライン翻訳を選べます。要約やAIチャットなどのAI機能にはインターネット接続が必要です。</p>' },
        { id: 'apple-watch', q: 'Apple Watchで録音できますか？',
          a: '<p>できます。iPhoneを持っていなくても、Apple Watch単体で録音できます。録音はあとでiPhoneへ転送され、文字起こしされます。1回に録音できる長さは、無料版で最大15分、Premiumで最大2時間です。</p>' },
        { id: 'quick-start', q: 'アプリを開かずにすぐ録音を始められますか？',
          a: '<p>ロック画面ウィジェットから、ワンタップで録音を始められます。iOS 18以降ではコントロールセンターにも追加できます。日本のiPhoneでは、iOS 26.2以降でサイドボタンの長押しにTexterの音声入力を割り当てられます。</p>' },
        { id: 'zoom', q: 'Zoomの録画は文字起こしできますか？',
          a: '<p>Zoomの録画リンクは直接取り込めません。録画ファイル（mp4やm4a）をダウンロードしてから、ファイルとして取り込んでください。</p>' },
      ],
    },
    {
      id: 'notes', title: '要約・タスク・書き出し', items: [
        { id: 'summary', q: '議事録や要約を自動で作れますか？',
          a: '<p>作れます。議事録・インタビュー・講義・構造化要約など20種類のテンプレートから選ぶと、文字起こしを目的に合った形の要約に整えます。長い会議の話題を一覧できる「話題マップ」や「ワードクラウド」もあります。</p>' },
        { id: 'action-items', q: '会議のタスク（アクションアイテム）を抜き出せますか？',
          a: '<p>できます。AIが文字起こしから「やること」を抽出し、担当者と期限も読み取って一覧にします。抽出したタスクはそのままリマインダーに登録でき、設定した日時に通知でお知らせします。</p>' },
        { id: 'ask-notes', q: '保存した記録にあとから質問できますか？',
          a: '<p>できます。AIチャット「ノートに聞く」で、ノートの内容について「決まった納期は？」のように質問できます。無料版は1日3回まで、Premiumでは回数の制限なく使えます。</p>' },
        { id: 'export', q: 'どんな形式で書き出せますか？',
          a: '<ul><li>ノート：テキスト、PDF、SRT字幕ファイル、字幕付き動画</li><li>要約：Markdown、テキスト、HTML、PDF</li></ul><p>SlackのWebhookを設定すると、文字起こし結果をSlackに投稿することもできます。</p>' },
      ],
    },
    {
      id: 'privacy', title: 'プライバシー・データの扱い', items: [
        { id: 'storage', q: '録音やノートはどこに保存されますか？',
          a: '<p>録音とノートは、お使いの端末内に保存されます。Texterのサーバーにノートを保管する同期機能はありません。機種変更やアプリの削除の前には、必要なノートを書き出しておいてください。</p>' },
        { id: 'data-sent', q: '音声やテキストが外部に送信されることはありますか？',
          a: '<p>クラウドで処理する機能を使うときだけ、処理に必要な音声やテキストを各サービスの提供事業者に送信します。対象は、会話向けのリアルタイム音声認識、WhisperとAmazon Transcribeによるファイルの文字起こし、翻訳、要約やAIチャットなどのAI機能です。リアルタイム音声認識とAI機能は、初めて使うときにアプリ内で送信先を説明し、同意を確認します。詳しくは<a href="/privacy-policy/">プライバシーポリシー</a>をご確認ください。</p>' },
        { id: 'ai-training', q: '要約やAIチャットに使ったノートは、AIの学習に使われますか？',
          a: '<p>要約・AIチャットなどのAI機能では、ノートのテキストをOpenAIのAPIに送信して回答を生成します。OpenAI APIのデータ利用ポリシーにもとづき、送信したデータはOpenAIのモデル学習には使われません。</p>' },
      ],
    },
  ],
};

const en = {
  path: '/en/faq/',
  home: '/en/',
  htmlLang: 'en',
  ogLocale: 'en_US',
  ogImage: '/img/ogp-en.png?v=3',
  appStore: 'https://apps.apple.com/app/id1482592304',
  title: 'FAQ | Texter - AI transcription & meeting notes app',
  description: 'Answers about Texter: supported devices, pricing, languages, speaker labels, Apple Watch recording, file import, and how your data is handled.',
  h1: 'Frequently asked questions',
  intro: 'Answers to common questions about Texter, the AI transcription and meeting notes app. For step-by-step instructions, see the <a href="https://texter-app.notion.site/faq-en" target="_blank" rel="noopener noreferrer">user guide (Notion)</a>.',
  updatedLabel: 'Last updated',
  tocTitle: 'Contents',
  crumb: 'FAQ',
  crumbLabel: 'Breadcrumb',
  skip: 'Skip to content',
  navLabel: 'Main',
  nav: [
    { label: 'Features', href: '/en/#record', opt: true },
    { label: 'Pricing', href: '/en/#pricing', opt: true },
    { label: '日本語', href: '/faq/', hreflang: 'ja' },
  ],
  ctaTitle: 'Just hit record at your next meeting.',
  ctaBody: 'Texter is free to start. For iPhone / iPad / Apple Watch / Mac (Apple Silicon) / Android.',
  footer: [
    { label: 'Home', href: '/en/' },
    { label: 'User guide', href: 'https://texter-app.notion.site/faq-en', ext: true },
    { label: 'Contact', href: 'mailto:texter.work.app@gmail.com' },
    { label: 'Terms of Service', href: '/en/terms-of-service/' },
    { label: 'Privacy Policy', href: '/en/privacy-policy/' },
    { label: '日本語', href: '/faq/', hreflang: 'ja' },
  ],
  sections: [
    {
      id: 'about', title: 'About Texter', items: [
        { id: 'what-is-texter', q: 'What is Texter?',
          a: '<p>Texter is an AI transcription and note-taking app that turns meetings, interviews, and lectures into notes. Record or import an audio or video file, and Texter transcribes it, labels speakers, summarizes it, and extracts action items. You can ask questions about your saved notes later with AI chat.</p>' },
        { id: 'devices', q: 'Which devices does Texter support?',
          a: '<ul><li>iPhone and iPad (iOS / iPadOS 16.0 or later)</li><li>Apple Watch (watchOS 11 or later)</li><li>Mac with Apple silicon (runs as the iPad app)</li><li>Android (on Google Play)</li></ul>' },
        { id: 'price', q: 'Is Texter free? How much is Premium?',
          a: '<p>The app is free to download, and the basic features are free to use. The free plan limits transcription time and how often you can use each feature.</p><p>Texter Premium raises those limits. On the Japanese App Store it is ¥1,800 per month, ¥8,800 per year, or ¥600 per week. Prices in other countries are shown in your local currency in the app. Check the purchase screen in the app for any free trial and its length.</p>' },
        { id: 'cancel', q: 'How do I cancel Premium?',
          a: '<p>On iPhone, open Settings, tap your name, then Subscriptions, then Texter. On Android, open Google Play, then Payments &amp; subscriptions, then Subscriptions. Deleting the app does not cancel your subscription.</p>' },
        { id: 'business', q: 'Can my company use Texter?',
          a: '<p>Yes. Our <a href="/assets/pdf/texter-for-business.pdf">business brochure (PDF)</a> covers features, pricing, and security. For questions, email <a href="mailto:texter.work.app@gmail.com">texter.work.app@gmail.com</a>.</p>' },
      ],
    },
    {
      id: 'transcription', title: 'Transcription', items: [
        { id: 'realtime', q: 'Can Texter transcribe a meeting live?',
          a: '<p>Yes. Tap record and your words appear as text while you talk. Depending on the language and your settings, Texter uses a cloud speech engine built for conversation or Apple speech recognition. The free plan limits how long each recording can be.</p>' },
        { id: 'import', q: 'Can I transcribe audio or video files I already have? Which formats work?',
          a: '<p>Yes. Supported formats:</p><ul><li>Audio: m4a, mp3, wav, aac, aiff, caf, and more</li><li>Video: mp4, mov, m4v</li></ul><p>You can also import from Google Drive, Dropbox, and OneDrive share links. Choose the engine: Whisper (OpenAI’s speech recognition model), Amazon Transcribe, or Apple SpeechAnalyzer, which runs on the device (iOS 26 or later). With Premium, each file can be up to 2 hours with Whisper or up to 4 hours with Amazon Transcribe. Amazon Transcribe also has a monthly usage allowance, separate from the per-file limit.</p>' },
        { id: 'speaker-diarization', q: 'Can Texter tell speakers apart?',
          a: '<p>Yes, with Premium. When you transcribe an audio or video file with Whisper or Amazon Transcribe, Texter separates the text by speaker. Amazon Transcribe distinguishes up to 10 speakers.</p>' },
        { id: 'languages', q: 'Which languages are supported?',
          a: '<p>File transcription with Whisper supports 99 languages plus automatic language detection. Live transcription works in the languages Apple speech recognition supports. For translation, choose DeepL or Google Translate.</p>' },
        { id: 'offline', q: 'Does Texter work offline?',
          a: '<p>Some features do. Without a network connection, live transcription switches to on-device Apple speech recognition (in languages that support it). On iOS 26 or later you can transcribe files with SpeechAnalyzer, which runs on the device. Translation can use Google’s offline mode. AI features such as summaries and AI chat need an internet connection.</p>' },
        { id: 'apple-watch', q: 'Can I record on Apple Watch?',
          a: '<p>Yes. Apple Watch records on its own, without your iPhone nearby. The recording transfers to your iPhone later and is transcribed there. Each recording can be up to 15 minutes on the free plan and up to 2 hours with Premium.</p>' },
        { id: 'quick-start', q: 'Can I start recording without opening the app?',
          a: '<p>Yes. Start recording with one tap from the Lock Screen widget. On iOS 18 or later you can also add Texter to Control Center.</p>' },
        { id: 'zoom', q: 'Can I transcribe a Zoom recording?',
          a: '<p>Zoom recording links can’t be imported directly. Download the recording file (mp4 or m4a) first, then import it as a file.</p>' },
      ],
    },
    {
      id: 'notes', title: 'Summaries, tasks, and export', items: [
        { id: 'summary', q: 'Can Texter write meeting minutes and summaries?',
          a: '<p>Yes. Pick one of 20 templates, such as meeting minutes, interview, lecture, or structured summary, and Texter turns the transcript into a summary in that format. A topic map and a word cloud give you an overview of long meetings.</p>' },
        { id: 'action-items', q: 'Can Texter pull out action items from a meeting?',
          a: '<p>Yes. AI finds the to-dos in the transcript, along with who owns each one and when it is due. Each task can become a reminder in one tap, and Texter notifies you at the time you set.</p>' },
        { id: 'ask-notes', q: 'Can I ask questions about my past recordings?',
          a: '<p>Yes. With AI chat, ask your notes things like “What deadline did we agree on?” The free plan allows 3 questions a day, and Premium has no daily limit.</p>' },
        { id: 'export', q: 'Which export formats are available?',
          a: '<ul><li>Notes: text, PDF, SRT subtitle file, video with captions</li><li>Summaries: Markdown, text, HTML, PDF</li></ul><p>You can also post transcripts to Slack by setting up a Slack webhook.</p>' },
      ],
    },
    {
      id: 'privacy', title: 'Privacy and your data', items: [
        { id: 'storage', q: 'Where are my recordings and notes stored?',
          a: '<p>Recordings and notes are stored on your device. Texter has no sync feature that keeps your notes on our servers. Export any notes you need before you switch phones or delete the app.</p>' },
        { id: 'data-sent', q: 'Is my audio or text ever sent outside the device?',
          a: '<p>Only when you use a feature that runs in the cloud. Texter then sends the audio or text that feature needs to its service provider. These features are conversational live transcription, file transcription with Whisper or Amazon Transcribe, translation, and AI features such as summaries and AI chat. The first time you use live transcription or an AI feature, the app explains where the data goes and asks for your consent. See the <a href="/en/privacy-policy/">Privacy Policy</a> for details.</p>' },
        { id: 'ai-training', q: 'Are notes I use with summaries or AI chat used to train AI models?',
          a: '<p>AI features such as summaries and AI chat send the note text to the OpenAI API to generate a response. Under the OpenAI API data usage policy, that data is not used to train OpenAI’s models.</p>' },
      ],
    },
  ],
};

module.exports = { updated, ja, en };
